spring.application.name=walletservice-merezh
server.port=8083

spring.datasource.url=jdbc:postgresql://postgres-walletservice:5432/walletservice-merezh
spring.datasource.username=postgres
spring.datasource.password=postgres123

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update